// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: cpfd-proto.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataGeneratorClient is the client API for DataGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataGeneratorClient interface {
	GenerateAllLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
}

type dataGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewDataGeneratorClient(cc grpc.ClientConnInterface) DataGeneratorClient {
	return &dataGeneratorClient{cc}
}

func (c *dataGeneratorClient) GenerateAllLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, "/proto.DataGenerator/GenerateAllLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataGeneratorServer is the server API for DataGenerator service.
// All implementations must embed UnimplementedDataGeneratorServer
// for forward compatibility
type DataGeneratorServer interface {
	GenerateAllLog(context.Context, *LogRequest) (*LogResponse, error)
	mustEmbedUnimplementedDataGeneratorServer()
}

// UnimplementedDataGeneratorServer must be embedded to have forward compatible implementations.
type UnimplementedDataGeneratorServer struct {
}

func (UnimplementedDataGeneratorServer) GenerateAllLog(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateAllLog not implemented")
}
func (UnimplementedDataGeneratorServer) mustEmbedUnimplementedDataGeneratorServer() {}

// UnsafeDataGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataGeneratorServer will
// result in compilation errors.
type UnsafeDataGeneratorServer interface {
	mustEmbedUnimplementedDataGeneratorServer()
}

func RegisterDataGeneratorServer(s grpc.ServiceRegistrar, srv DataGeneratorServer) {
	s.RegisterService(&DataGenerator_ServiceDesc, srv)
}

func _DataGenerator_GenerateAllLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataGeneratorServer).GenerateAllLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DataGenerator/GenerateAllLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataGeneratorServer).GenerateAllLog(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataGenerator_ServiceDesc is the grpc.ServiceDesc for DataGenerator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataGenerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DataGenerator",
	HandlerType: (*DataGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateAllLog",
			Handler:    _DataGenerator_GenerateAllLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cpfd-proto.proto",
}
